# Generated by Django 5.2.6 on 2025-09-26 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du tableau de bord')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('widgets_config', models.JSONField(default=list, verbose_name='Configuration des widgets')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('is_default', models.BooleanField(default=False, verbose_name='Tableau par défaut')),
                ('allowed_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs autorisés')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Tableau de bord',
                'verbose_name_plural': 'Tableaux de bord',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du rapport')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('report_type', models.CharField(choices=[('members_report', 'Rapport des membres'), ('financial_report', 'Rapport financier'), ('inventory_report', 'Rapport de stock'), ('sales_report', 'Rapport des ventes'), ('loan_report', 'Rapport des prêts'), ('custom_report', 'Rapport personnalisé')], max_length=50, verbose_name='Type de rapport')),
                ('parameters', models.JSONField(default=dict, verbose_name='Paramètres')),
                ('period_start', models.DateField(verbose_name='Début de période')),
                ('period_end', models.DateField(verbose_name='Fin de période')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin du fichier')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10, verbose_name='Format de fichier')),
                ('generation_time', models.DateTimeField(verbose_name='Heure de génération')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Taille du fichier (bytes)')),
                ('status', models.CharField(choices=[('generating', 'En cours de génération'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='generating', max_length=20, verbose_name='Statut')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-generation_time'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('description', models.TextField(verbose_name='Description')),
                ('report_type', models.CharField(choices=[('members_report', 'Rapport des membres'), ('financial_report', 'Rapport financier'), ('inventory_report', 'Rapport de stock'), ('sales_report', 'Rapport des ventes'), ('loan_report', 'Rapport des prêts')], max_length=50, verbose_name='Type de rapport')),
                ('template_config', models.JSONField(default=dict, verbose_name='Configuration du modèle')),
                ('default_parameters', models.JSONField(default=dict, verbose_name='Paramètres par défaut')),
                ('html_template', models.TextField(blank=True, verbose_name='Template HTML')),
                ('css_styles', models.TextField(blank=True, verbose_name='Styles CSS')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Modèle de rapport',
                'verbose_name_plural': 'Modèles de rapports',
            },
        ),
    ]
