# Generated by Django 5.2.6 on 2025-09-26 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code comptable')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du compte')),
                ('account_type', models.CharField(choices=[('asset', 'Actif'), ('liability', 'Passif'), ('equity', 'Capitaux propres'), ('revenue', 'Produits'), ('expense', 'Charges')], max_length=20, verbose_name='Type de compte')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Solde')),
                ('is_reconcilable', models.BooleanField(default=False, verbose_name='Rapprochable')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.account', verbose_name='Compte parent')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du budget')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('total_revenue_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget recettes')),
                ('total_expense_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget dépenses')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('closed', 'Fermé')], default='draft', max_length=20, verbose_name='Statut')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('transaction_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de transaction')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('transaction_type', models.CharField(choices=[('income', 'Recette'), ('expense', 'Dépense'), ('transfer', 'Transfert'), ('loan', 'Prêt'), ('loan_repayment', 'Remboursement prêt'), ('membership_fee', 'Cotisation'), ('dividend', 'Dividende')], max_length=20, verbose_name='Type de transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('reference_type', models.CharField(blank=True, choices=[('sale', 'Vente'), ('purchase', 'Achat'), ('member_fee', 'Cotisation membre'), ('loan', 'Prêt'), ('other', 'Autre')], max_length=20, verbose_name='Type de référence')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='Rapproché')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='finance.account', verbose_name='Compte crédit')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_transactions', to='finance.account', verbose_name='Compte débit')),
            ],
            options={
                'verbose_name': 'Transaction financière',
                'verbose_name_plural': 'Transactions financières',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('loan_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de prêt')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant principal')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Taux d'intérêt (%)")),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total')),
                ('application_date', models.DateField(verbose_name='Date de demande')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('disbursement_date', models.DateField(blank=True, null=True, verbose_name='Date de déblocage')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('disbursed', 'Débloqué'), ('active', 'Actif'), ('completed', 'Terminé'), ('defaulted', 'En défaut'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Paiement mensuel')),
                ('balance_remaining', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Solde restant')),
                ('collateral_description', models.TextField(blank=True, verbose_name='Description des garanties')),
                ('purpose', models.TextField(verbose_name='Objet du prêt')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('guarantor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_loans1', to='members.member', verbose_name='Garant 1')),
                ('guarantor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_loans2', to='members.member', verbose_name='Garant 2')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Prêt',
                'verbose_name_plural': 'Prêts',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capital')),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Intérêts')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pénalités')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Solde après')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de reçu')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.loan', verbose_name='Prêt')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reçu par')),
            ],
            options={
                'verbose_name': 'Remboursement de prêt',
                'verbose_name_plural': 'Remboursements de prêts',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='MemberSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('account_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de compte')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name="Taux d'intérêt (%)")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('closed', 'Fermé')], default='active', max_length=20, verbose_name='Statut')),
                ('opening_date', models.DateField(verbose_name="Date d'ouverture")),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Date de fermeture')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Épargne membre',
                'verbose_name_plural': 'Épargnes des membres',
            },
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Dépôt'), ('withdrawal', 'Retrait'), ('interest', 'Intérêts'), ('fee', 'Frais')], max_length=20, verbose_name='Type de transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Solde après')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('savings_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.membersavings', verbose_name="Compte d'épargne")),
            ],
            options={
                'verbose_name': "Transaction d'épargne",
                'verbose_name_plural': "Transactions d'épargne",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant budgété')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant réel')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account', verbose_name='Compte')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.budget', verbose_name='Budget')),
            ],
            options={
                'verbose_name': 'Ligne de budget',
                'verbose_name_plural': 'Lignes de budget',
                'unique_together': {('budget', 'account')},
            },
        ),
    ]
