# Generated by Django 5.2.6 on 2025-09-26 00:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, help_text='Désélectionner pour désactiver sans supprimer.', verbose_name='Actif')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='finance.accountcategory', verbose_name='Catégorie parent')),
            ],
            options={
                'verbose_name': 'Catégorie de compte',
                'verbose_name_plural': 'Catégories de comptes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, help_text='Désélectionner pour désactiver sans supprimer.', verbose_name='Actif')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du compte')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code comptable')),
                ('account_type', models.CharField(choices=[('asset', 'Actif'), ('liability', 'Passif'), ('equity', 'Capitaux propres'), ('revenue', 'Produits'), ('expense', 'Charges')], max_length=20, verbose_name='Type de compte')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_system', models.BooleanField(default=False, help_text='Ne peut pas être supprimé', verbose_name='Compte système')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Solde actuel')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.accountcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MemberLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, help_text='Désélectionner pour désactiver sans supprimer.', verbose_name='Actif')),
                ('loan_number', models.CharField(help_text='Généré automatiquement', max_length=20, unique=True, verbose_name='Numéro de prêt')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Montant demandé')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Montant approuvé')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde restant')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Taux d'intérêt (%)")),
                ('term_months', models.PositiveIntegerField(verbose_name='Durée (mois)')),
                ('application_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de demande')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('disbursement_date', models.DateField(blank=True, null=True, verbose_name='Date de déboursement')),
                ('maturity_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('disbursed', 'Déboursé'), ('active', 'Actif'), ('completed', 'Remboursé'), ('defaulted', 'En défaut'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('purpose', models.TextField(verbose_name='Objet du prêt')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Prêt membre',
                'verbose_name_plural': 'Prêts membres',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, help_text='Désélectionner pour désactiver sans supprimer.', verbose_name='Actif')),
                ('transaction_number', models.CharField(help_text='Généré automatiquement', max_length=20, unique=True, verbose_name='Numéro de transaction')),
                ('transaction_type', models.CharField(choices=[('income', 'Recette'), ('expense', 'Dépense'), ('transfer', 'Transfert'), ('adjustment', 'Ajustement')], max_length=20, verbose_name='Type de transaction')),
                ('source', models.CharField(choices=[('manual', 'Saisie manuelle'), ('sale', 'Vente'), ('purchase', 'Achat'), ('membership_fee', 'Cotisation'), ('loan', 'Prêt'), ('dividend', 'Dividende'), ('donation', 'Don'), ('other', 'Autre')], default='manual', max_length=20, verbose_name='Source')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de transaction')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Date de valeur')),
                ('description', models.TextField(verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('external_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence externe')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='Rapproché')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='finance.account', verbose_name='Compte crédité')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_transactions', to='finance.account', verbose_name='Compte débité')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member', verbose_name='Membre concerné')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale', verbose_name='Vente associée')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Transaction financière',
                'verbose_name_plural': 'Transactions financières',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['transaction_number'], name='finance_fin_transac_b0c048_idx'), models.Index(fields=['transaction_date'], name='finance_fin_transac_36d0df_idx'), models.Index(fields=['debit_account', 'transaction_date'], name='finance_fin_debit_a_0dff0b_idx'), models.Index(fields=['credit_account', 'transaction_date'], name='finance_fin_credit__897087_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemberSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, help_text='Désélectionner pour désactiver sans supprimer.', verbose_name='Actif')),
                ('savings_type', models.CharField(choices=[('regular', 'Épargne courante'), ('term', 'Épargne à terme'), ('special', 'Épargne spéciale')], default='regular', max_length=20, verbose_name="Type d'épargne")),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde actuel')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Taux d'intérêt (%)")),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde minimum')),
                ('opening_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'ouverture")),
                ('maturity_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('last_interest_date', models.DateField(blank=True, null=True, verbose_name='Dernière capitalisation')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Épargne membre',
                'verbose_name_plural': 'Épargnes membres',
                'unique_together': {('member', 'savings_type')},
            },
        ),
    ]
