# Generated by Django 5.2.6 on 2025-09-26 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='Abréviation')),
                ('unit_type', models.CharField(choices=[('weight', 'Poids'), ('volume', 'Volume'), ('length', 'Longueur'), ('unit', 'Unité'), ('other', 'Autre')], max_length=20, verbose_name="Type d'unité")),
            ],
            options={
                'verbose_name': 'Unité de mesure',
                'verbose_name_plural': 'Unités de mesure',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category', verbose_name='Catégorie parent')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'inventaire")),
                ('date_start', models.DateTimeField(verbose_name='Date de début')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='planned', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Code produit (SKU)')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Code-barres')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de revient')),
                ('selling_price_member', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix membre')),
                ('selling_price_non_member', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix non-membre')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Stock actuel')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Stock minimum')),
                ('maximum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Stock maximum')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('discontinued', 'Arrêté')], default='active', max_length=20, verbose_name='Statut')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category', verbose_name='Catégorie')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unit', verbose_name='Unité de base')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('movement_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('adjustment', 'Ajustement'), ('transfer', 'Transfert')], max_length=20, verbose_name='Type de mouvement')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantité')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coût unitaire')),
                ('reference_type', models.CharField(choices=[('purchase', 'Achat'), ('sale', 'Vente'), ('production', 'Production'), ('loss', 'Perte'), ('inventory', 'Inventaire'), ('donation', 'Don')], max_length=20, verbose_name='Type de référence')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('stock_after', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Stock après')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='Produit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('theoretical_quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantité théorique')),
                ('physical_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Quantité physique')),
                ('difference', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Écart')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Compté par')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventory', verbose_name='Inventaire')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
                'unique_together': {('inventory', 'product')},
            },
        ),
    ]
