# Generated by Django 5.2.6 on 2025-09-26 00:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, help_text='Désélectionner pour désactiver sans supprimer.', verbose_name='Actif')),
                ('customer_code', models.CharField(help_text='Généré automatiquement', max_length=20, unique=True, verbose_name='Code client')),
                ('customer_type', models.CharField(choices=[('member', 'Membre'), ('external', 'Externe'), ('corporate', 'Entreprise')], default='external', max_length=20, verbose_name='Type de client')),
                ('name', models.CharField(max_length=200, verbose_name='Nom/Raison sociale')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Personne de contact')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Limite de crédit')),
                ('payment_terms_days', models.PositiveIntegerField(default=0, verbose_name='Délai de paiement (jours)')),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total des achats')),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True, verbose_name='Dernier achat')),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='Membre associé')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, help_text='Désélectionner pour désactiver sans supprimer.', verbose_name='Actif')),
                ('sale_number', models.CharField(help_text='Généré automatiquement', max_length=20, unique=True, verbose_name='Numéro de vente')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de vente')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='Date de livraison réelle')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('confirmed', 'Confirmée'), ('delivered', 'Livrée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('partial', 'Partiel'), ('paid', 'Payé'), ('overdue', 'En retard')], default='pending', max_length=20, verbose_name='Statut de paiement')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Sous-total')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Remise (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant de remise')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxe (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant de taxe')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant total')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant payé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.customer', verbose_name='Client')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, help_text='Désélectionner pour désactiver sans supprimer.', verbose_name='Actif')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Remise ligne (%)')),
                ('lot_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de lot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Produit')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale', verbose_name='Vente')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, help_text='Désélectionner pour désactiver sans supprimer.', verbose_name='Actif')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('check', 'Chèque'), ('card', 'Carte bancaire'), ('credit', 'À crédit')], max_length=20, verbose_name='Mode de paiement')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale', verbose_name='Vente')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Paiement de vente',
                'verbose_name_plural': 'Paiements de vente',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_number'], name='sales_sale_sale_nu_99d8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer', 'sale_date'], name='sales_sale_custome_e35bee_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='sales_sale_sale_da_2fd927_idx'),
        ),
    ]
