# Generated by Django 5.2.6 on 2025-09-26 17:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cotisation mensuelle')),
                ('benefits', models.JSONField(default=list, verbose_name='Avantages')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Type d'adhésion",
                'verbose_name_plural': "Types d'adhésion",
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('membership_number', models.CharField(max_length=20, unique=True, verbose_name="Numéro d'adhésion")),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('nationality', models.CharField(default='Sénégalaise', max_length=50, verbose_name='Nationalité')),
                ('id_number', models.CharField(max_length=30, verbose_name='Numéro CNI/Passeport')),
                ('profession', models.CharField(max_length=100, verbose_name='Profession')),
                ('emergency_contact_name', models.CharField(max_length=200, verbose_name="Contact d'urgence (nom)")),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name="Contact d'urgence (téléphone)")),
                ('emergency_contact_relation', models.CharField(max_length=50, verbose_name='Relation')),
                ('join_date', models.DateField(verbose_name="Date d'adhésion")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('inactive', 'Inactif'), ('honorary', 'Honoraire')], default='active', max_length=20, verbose_name='Statut')),
                ('skills', models.JSONField(default=list, verbose_name='Compétences')),
                ('specialties', models.JSONField(default=list, verbose_name='Spécialités')),
                ('photo', models.ImageField(blank=True, upload_to='members/photos/', verbose_name='Photo')),
                ('id_document', models.FileField(blank=True, upload_to='members/documents/', verbose_name="Document d'identité")),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.address', verbose_name='Adresse')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contact', verbose_name='Contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.membershiptype', verbose_name="Type d'adhésion")),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['membership_number'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('relationship', models.CharField(choices=[('spouse', 'Époux/Épouse'), ('child', 'Enfant'), ('parent', 'Parent'), ('sibling', 'Frère/Sœur'), ('other', 'Autre')], max_length=20, verbose_name='Relation')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Membre de famille',
                'verbose_name_plural': 'Membres de famille',
            },
        ),
        migrations.CreateModel(
            name='MembershipFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('period_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois')),
                ('period_year', models.PositiveIntegerField(verbose_name='Année')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('mobile', 'Mobile Money'), ('bank', 'Virement bancaire'), ('check', 'Chèque')], max_length=20, verbose_name='Mode de paiement')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de reçu')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('member', 'period_month', 'period_year')},
            },
        ),
    ]
