# Generated by Django 5.2.6 on 2025-09-26 00:15

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, help_text='Désélectionner pour désactiver sans supprimer.', verbose_name='Actif')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cotisation mensuelle')),
                ('benefits', models.TextField(blank=True, verbose_name='Avantages')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Couleur')),
            ],
            options={
                'verbose_name': "Type d'adhésion",
                'verbose_name_plural': "Types d'adhésion",
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, help_text='Désélectionner pour désactiver sans supprimer.', verbose_name='Actif')),
                ('member_number', models.CharField(help_text='Généré automatiquement', max_length=20, unique=True, verbose_name='Numéro de membre')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, verbose_name='Sexe')),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name="Pièce d'identité")),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('divorced', 'Divorcé(e)'), ('widowed', 'Veuf/Veuve')], max_length=20, verbose_name='Situation matrimoniale')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='Photo')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='members/documents/', verbose_name="Document d'identité")),
                ('join_date', models.DateField(default=datetime.date.today, verbose_name="Date d'adhésion")),
                ('membership_number', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'adhésion")),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('specialties', models.TextField(blank=True, help_text='Compétences particulières du membre', verbose_name='Spécialités/Compétences')),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name="Années d'expérience")),
                ('dependents_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Nombre de personnes à charge')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name="Contact d'urgence - Nom")),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name="Contact d'urgence - Téléphone")),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100, verbose_name="Contact d'urgence - Relation")),
                ('is_founder', models.BooleanField(default=False, verbose_name='Membre fondateur')),
                ('is_board_member', models.BooleanField(default=False, verbose_name='Membre du conseil')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address', verbose_name='Adresse')),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contactinfo', verbose_name='Contact')),
                ('user', models.OneToOneField(blank=True, help_text='Compte utilisateur associé (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.membershiptype', verbose_name="Type d'adhésion")),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, help_text='Désélectionner pour désactiver sans supprimer.', verbose_name='Actif')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('overdue', 'En retard'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Paiement de cotisation',
                'verbose_name_plural': 'Paiements de cotisations',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='MembershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, help_text='Désélectionner pour désactiver sans supprimer.', verbose_name='Actif')),
                ('change_date', models.DateField(default=datetime.date.today, verbose_name='Date du changement')),
                ('reason', models.TextField(blank=True, verbose_name='Motif du changement')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to='members.member', verbose_name='Membre')),
                ('new_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_memberships', to='members.membershiptype', verbose_name='Nouveau type')),
                ('old_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_memberships', to='members.membershiptype', verbose_name='Ancien type')),
            ],
            options={
                'verbose_name': "Historique d'adhésion",
                'verbose_name_plural': "Historiques d'adhésion",
                'ordering': ['-change_date'],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_number'], name='members_mem_member__425bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['last_name', 'first_name'], name='members_mem_last_na_92a910_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['join_date'], name='members_mem_join_da_84098f_idx'),
        ),
    ]
