# Generated by Django 5.2.6 on 2025-09-26 00:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, help_text='Désélectionner pour désactiver sans supprimer.', verbose_name='Actif')),
                ('street', models.CharField(max_length=255, verbose_name='Rue')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Région/État')),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100, verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, help_text='Désélectionner pour désactiver sans supprimer.', verbose_name='Actif')),
                ('phone_primary', models.CharField(max_length=20, verbose_name='Téléphone principal')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name='Téléphone secondaire')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='CooperativeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, help_text='Désélectionner pour désactiver sans supprimer.', verbose_name='Actif')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la coopérative')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='Raison sociale')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'enregistrement")),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Numéro fiscal')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cooperative/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('currency', models.CharField(default='XOF', max_length=10, verbose_name='Devise')),
                ('default_member_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cotisation par défaut')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address', verbose_name='Adresse')),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contactinfo', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Information coopérative',
                'verbose_name_plural': 'Informations coopérative',
            },
        ),
    ]
